HrBjarup/Fog-Carport

- FogCarport/src/main/webapp/javascript/OrderValidation.js
> Added comment in the js-file to explain SWAL

- FogCarport/src/main/java/logic/PartslistLogic.java
When customer inputs the order, it is input in CM.
When we handle it internally in the code, it's easier if it is in MM currently.
So convert it to MM.
> Change CM from Order to MM.

- docs/Database docs/create.sql
Added first version of database DDL script to the project
> Initial createscript for DB added to project

- FogCarport/src/main/java/logic/ShedLogic.java
- FogCarport/src/main/java/logic/drawings/SVGDrawingShed.java
- FogCarport/src/main/webapp/svg/shed.jsp
- FogCarport/src/test/java/logic/ShedLogicTest.java
> Testing for Shed Algorithm done.

- FogCarport/src/main/java/logic/BaseCalc.java
- FogCarport/src/test/java/logic/BaseCalcTest.java
Unfinished version of the base algorithm
> Task#34 - Base algorithm - unfinished

- FogCarport/src/main/java/data/DataFacade.java
- FogCarport/src/main/java/data/DataFacadeImpl.java
- FogCarport/src/main/java/data/databaseAccessObjects/mappers/OrderMapper.java
- FogCarport/src/main/java/logic/LogicFacade.java
- FogCarport/src/main/java/logic/LogicFacadeImpl.java
- FogCarport/src/main/java/presentation/Command.java
- FogCarport/src/main/java/presentation/viewAllOrders.java
- FogCarport/src/main/java/presentation/viewOrder.java
- FogCarport/src/main/webapp/allOrders.jsp
- FogCarport/src/main/webapp/navbar.jsp
- FogCarport/src/main/webapp/viewOrder.jsp
Please enhance the code or improve the visuals if you wish. Personally think the visuals on the "se alle ordrer" isn't the best and could use some improvement.
The work is on [this branch.]( https://github.com/HrBjarup/Fog-Carport/tree/Task%23114SeeOrders)
[The Task.](https://tree.taiga.io/project/maltemagnussen-fog/task/114?kanban-status=1592821)
[The User-Story.](https://tree.taiga.io/project/maltemagnussen-fog/us/6?milestone=230234)
**Should maybe contain Customer info and Employee info instead of their IDs.**
Made **[this task](https://tree.taiga.io/project/maltemagnussen-fog/task/117?kanban-status=1592820)** for it. When that is finished, then you can implement the info about Customer and Employee better, instead of just a number.
**User info:**
**Employee info:**
> Able to see all orders and choose a single one and view its details.

- FogCarport/src/main/java/data/DataFacade.java
- FogCarport/src/main/java/data/DataFacadeImpl.java
- FogCarport/src/main/java/data/databaseAccessObjects/mappers/UserMapper.java
- FogCarport/src/main/java/data/models/CustomerModel.java
- FogCarport/src/main/java/data/models/EmployeeModel.java
- FogCarport/src/main/java/logic/Calculations/ShedLogic.java
- FogCarport/src/main/java/logic/LogicFacade.java
- FogCarport/src/main/java/logic/LogicFacadeImpl.java
- FogCarport/src/main/java/logic/drawings/SVGDrawingShed.java
- FogCarport/src/main/java/presentation/viewOrder.java
- FogCarport/src/main/webapp/viewOrder.jsp
Also added structure for it in the code.
Example of the view:
> View Employee and Customer attached to an Order.

- FogCarport/src/main/webapp/makeCarport.jsp
> Added customer info to .jsp.

- FogCarport/src/main/java/data/models/PartslistModel.java
If needed/wanted the partslistmodel can be expanded to hold a shared screwcount. This first expansion is made so the SVG for the roof can be implemented.
> Changes to PartslistModel - can be further expanded to hold more fields

- FogCarport/src/main/java/logic/LogicFacade.java
- FogCarport/src/main/java/logic/LogicFacadeImpl.java
- FogCarport/src/main/java/presentation/Command.java
- FogCarport/src/main/java/presentation/viewAllOrders.java
- FogCarport/src/main/java/presentation/viewOrder.java
- FogCarport/src/main/java/presentation/viewPartslist.java
- FogCarport/src/main/java/presentation/viewSVG.java
- FogCarport/src/main/webapp/navbar.jsp
- FogCarport/src/main/webapp/partslist.jsp
- FogCarport/src/main/webapp/viewOrder.jsp
- FogCarport/src/main/webapp/viewSVG.jsp
[This task is finished.](https://tree.taiga.io/project/maltemagnussen-fog/task/125?kanban-status=1592821)
Also added the back button.
Currently the stykliste button throws a not implemented yet error, because this method in LogicFacade isn't implemented yet. 
Also added this for the [SVG drawing.](https://tree.taiga.io/project/maltemagnussen-fog/task/124?kanban-status=1592821)
And that page also has a back button, and that command is also not implemented yet.
**Any suggestions for changes? Please give feedback and I'll push updates, or just hop on the branch and fix it yourself if you want :)**
> View partslist and view SVG buttons.

- FogCarport/src/main/webapp/homepage.jsp
> Fixed Issue #74

- FogCarport/src/main/webapp/javascript/OrderValidationShed.js
Fixed double amount of options in shed menu dropdowns
> Shed dropdown fixed (Issue#72 fixed)

- FogCarport/src/main/java/logic/Calculations/BaseCalc.java
- FogCarport/src/main/java/logic/Calculations/RoofFlatCalc.java
- FogCarport/src/main/java/logic/Calculations/ShedLogic.java
- FogCarport/src/main/java/logic/LogicFacade.java
- FogCarport/src/main/java/logic/LogicFacadeImpl.java
- FogCarport/src/main/java/logic/drawings/SVGDrawingShed.java
- FogCarport/src/main/java/presentation/Command.java
- FogCarport/src/main/java/presentation/FrontController.java
- FogCarport/src/main/java/presentation/makeCarportSimple.java
- FogCarport/src/main/java/presentation/orderCarport.java
- FogCarport/src/main/java/presentation/viewPartslist.java
- FogCarport/src/main/java/presentation/viewSVG.java
- FogCarport/src/main/webapp/allOrders.jsp
- FogCarport/src/main/webapp/makeCarport.jsp
- FogCarport/src/main/webapp/navbar.jsp
- FogCarport/src/main/webapp/viewOrder.jsp
- FogCarport/src/main/webapp/viewSVG.jsp
- FogCarport/src/test/java/logic/Calculations/BaseCalcTest.java
- FogCarport/src/test/java/logic/Calculations/ShedLogicTest.java
Extension of #83:
> [This task.](https://tree.taiga.io/project/maltemagnussen-fog/task/127?kanban-status=1592823)
> Some issues I fixed:
>  - Every material got added to the Partslist twice. 
>  - Both flat roof, tilted roof and shed got added to the partslist no matter if needed or not.
>  - We didn't catch AlgorithmException.
>  - Removed singleton from ShedLogic
>  - Added more guards to Shed stuff.
>  - Fixed the tests that got shafted by these changes.
Added [this task.](https://tree.taiga.io/project/maltemagnussen-fog/task/102?kanban-status=1592821)
makeCarport.jsp now orders an advanced carport, instead of a simple one. 
Finally found the time to make some of the .jsp slightly prettier aswell.
> SVG drawing jsp and structure

- FogCarport/src/main/java/logic/Calculations/BaseCalc.java
Combined SVG - Base and shed is combined, roof is separate
> Combined SVG

- FogCarport/src/main/java/logic/Calculations/BaseCalc.java
The SVG drawing for the base carport construction should now work for all types of carports (except the ones with a full-size shed)
> Fixed bug in SVG drawing Base missing posts

- FogCarport/src/main/webapp/javascript/global.js
Fixed shed input returning the wrong input for dimensions. The problem occurred in the JS.
> Fixed shed part of Issue#104

- FogCarport/src/main/java/presentation/Validation.java
- FogCarport/src/main/java/presentation/link.java
- FogCarport/src/main/java/presentation/login.java
- FogCarport/src/main/java/presentation/orderCarport.java
- FogCarport/src/main/java/presentation/viewOrder.java
- FogCarport/src/main/java/presentation/viewSVG.java
Input validation on user input in Presentation on Command classes.
> Validation

- FogCarport/src/main/java/presentation/Command.java
- FogCarport/src/main/java/presentation/makeCarport.java
- FogCarport/src/main/java/presentation/makeCarportForm.java
- FogCarport/src/main/webapp/homepage.jsp
- FogCarport/src/main/webapp/navbar.jsp
- extraFiles/Database docs/insertion(DML).sql
due to "orderCarport" already using "makeCarport" as its command name, I instead chose "makeCarportForm"
To use this command you must then use reference:  
`command=makeCarportForm`
tested and working with JSTL. Have not tried **Javascript**.
> issue#90 - makeCarport has its own command.

- FogCarport/src/main/java/data/databaseAccessObjects/mappers/OrderMapper.java
- FogCarport/src/main/java/data/databaseAccessObjects/mappers/UserMapper.java
- FogCarport/src/main/java/logic/Calculations/ShedLogic.java
- FogCarport/src/main/java/logic/drawings/SVGDrawingShed.java
> JavaDoc for ShedLogic and ShedDrawing

- FogCarport/src/main/java/logic/LogicFacade.java
- FogCarport/src/main/java/logic/LogicFacadeImpl.java
- FogCarport/src/main/java/logic/drawings/SVGDrawingBase.java
- FogCarport/src/main/java/logic/drawings/SVGDrawingRaisedRoof.java
- FogCarport/src/main/java/presentation/viewSVG.java
- FogCarport/src/main/webapp/viewSVG.jsp
> Task#148 viewSVG dynamic

- FogCarport/src/main/java/data/DataFacade.java
- FogCarport/src/main/java/data/DataFacadeImpl.java
- FogCarport/src/main/java/data/databaseAccessObjects/mappers/UserMapper.java
- FogCarport/src/main/java/data/models/EmployeeModel.java
- FogCarport/src/main/java/logic/LogicFacade.java
- FogCarport/src/main/java/logic/LogicFacadeImpl.java
- FogCarport/src/main/java/presentation/login.java
- extraFiles/Database docs/create(DDL).sql
- extraFiles/Database docs/insertion(DML).sql
Employees can now login - the can't do anything on the website yet, that belongs to other user tasks.
> Employee login

- FogCarport/src/main/java/presentation/FrontController.java
- FogCarport/src/main/java/presentation/payOrder.java
- FogCarport/src/main/java/presentation/viewAllOrders.java
- FogCarport/src/main/webapp/navbar.jsp
- FogCarport/src/main/webapp/viewOrder.jsp
Employee can now:
* see a list of all orders
* pay specific orders
* see partslist and svg for specific orders
* log out
all functionality that worked for customer before still works for customer (customer still cannot order carport without shed)
> Emp can now use the site

- FogCarport/src/main/java/logic/LogicFacade.java
- FogCarport/src/main/java/logic/LogicFacadeImpl.java
- FogCarport/src/main/java/logic/drawings/SVGDrawingBase.java
- FogCarport/src/main/java/logic/drawings/SVGDrawingShed.java
- FogCarport/src/main/java/presentation/viewSVG.java
- FogCarport/src/main/webapp/viewSVG.jsp
Fixed [Issue 125](https://github.com/HrBjarup/Fog-Carport/issues/125).
> Improvements to viewSVG

- FogCarport/src/main/java/data/databaseAccessObjects/mappers/MaterialMapper.java
- FogCarport/src/main/java/data/databaseAccessObjects/mappers/OrderMapper.java
- FogCarport/src/main/java/data/databaseAccessObjects/mappers/UserMapper.java
We think we don't close our connections, so we try to put preparedstatement into the try-with so it automatically closes.
The ResultSet will close automatically when its preparedStatement closes, according to it's JavaDoc.
> Attempted fix for "too many connections" error.

- FogCarport/src/main/webapp/viewSVG.jsp
> Combined all SVG

- FogCarport/src/main/webapp/navbar.jsp
> Fix for Issue#141

- FogCarport/src/main/java/data/databaseAccessObjects/mappers/MaterialMapper.java
- FogCarport/src/main/java/data/databaseAccessObjects/mappers/OrderMapper.java
- FogCarport/src/main/java/data/databaseAccessObjects/mappers/UserMapper.java
- FogCarport/src/main/java/logic/Calculations/RoofRaisedCalc.java
- FogCarport/src/main/java/logic/Calculations/ShedLogic.java
> Translated throwable exception messages to danish because user will see them.

- FogCarport/src/main/java/presentation/viewOrder.java
- FogCarport/src/main/webapp/css/global.css
- FogCarport/src/main/webapp/javascript/global.js
- FogCarport/src/main/webapp/partslist.jsp
- FogCarport/src/main/webapp/viewOrder.jsp
Customer can no longer see purchase purchase prices
Added a field for special price offers and js for this.
This will be saved through mappers and to database (Orders) in the future
> US19: #207, #232

- FogCarport/src/main/webapp/css/global.css
- FogCarport/src/main/webapp/javascript/global.js
- FogCarport/src/main/webapp/viewOrder.jsp
- FogCarport/src/main/webapp/viewSVG.jsp
The JS still needs the submit method on viewOrder.jsp to be a GET-method in order to work properly.
> Issue#158 Improvements to viewSVG

- FogCarport/src/main/java/presentation/viewOrder.java
Added ID check on order and user in session making it impossible to view orders that aren't your own (when logged in as customer)
> Customers can now only view their own orders

- FogCarport/src/main/java/logic/drawings/SVGDrawingRaisedRoof.java
> First edt of raisedroof design changes

- FogCarport/src/main/java/data/models/EmployeeModel.java
- FogCarport/src/main/java/presentation/login.java
- FogCarport/src/main/webapp/css/global.css
- FogCarport/src/main/webapp/navbar.jsp
[Task#257](https://tree.taiga.io/project/maltemagnussen-fog/task/257)
This was a newly created task I made to take my mind off of my algorithm refactoring. Hope thats OK!
[All elements shown, also error message]
[All elements shown, also error message]
Added \<strong> tag:
Removed pointless text (**discuss**)
> task#257: add greetings message to navbar

- FogCarport/src/main/webapp/javascript/global.js
Improved the JS checks on all the input fields on the homepage (all the checks that make sure to enable / disable the submit button)
> Improved JS validation for homepage.jsp

- FogCarport/src/main/webapp/viewOrder.jsp
Fixed with direct translation in the jsp
> Quickfix for issue#183

- FogCarport/src/main/java/presentation/orderCarport.java
- FogCarport/src/main/webapp/homepage.jsp
- FogCarport/src/main/webapp/javascript/global.js
Fixed JS for homepage.jps. Added a lot of if-cases that make sure the JS won't create errors and block other parts of the JS that is needed somewhere else on other pages
> Improved JS and fixed Issue#187

- FogCarport/src/main/java/data/databaseAccessObjects/mappers/UserMapper.java
- FogCarport/src/main/java/presentation/FrontController.java
- extraFiles/Database docs/create(DDL).sql
fix for issue https://github.com/HrBjarup/Fog-Carport/issues/162 (FrontController Exception Handling)
fix for issue https://github.com/HrBjarup/Fog-Carport/issues/181 (ZEROFILL IN DB)
UserException sends to Login
Data-/AlgorithmException sends to error page.
SQL scripts now take ZEROFILL on `id_order` into account, including the `bills`-table to avoid `foreign key constraint`-errors.
Tested working.
> Issues #162 & #181

- extraFiles/Database docs/insertion(DML).sql
testuser has all orders, id 6
`test@test.dk`|`1234`
**price is -1 until order is visited by an user**
> dml update after order change
